build_from:
  armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Filebeat"
  org.opencontainers.image.description: "Ships home-assistant.log (core) and/or journal logs to Elasticsearch server"
  org.opencontainers.image.source: "https://github.com/maretodoric/hassio-filebeat"
  org.opencontainers.image.licenses: "Apache License 2.0"
